spring:
  application:
    name: location-based service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false

opinet:
  api-key: ${OPINET_API_KEY}
  user-id: ${OPINET_USER_ID}
  password: ${OPINET_PASSWORD}

kakao:
  api-key: ${KAKAO_API_KEY}
